### ISSUE TITLE
calling logOut() in route guard not working

### ISSUE THREAD

**Issue by ricklang** [benbaran/adal-angular6-example#3]
I am using your library for Angular 6 application. I have a question about the logout function. I try to do something in my guard to check authorization after authentication:

```
canActivate(next: ActivatedRouteSnapshot,
                    state: RouterStateSnapshot): Observable<boolean> | Promise<boolean> | boolean {
    if ( this.adalService.userInfo.authenticated ) {
        if ( !getUserAuthorizationFromDB() ) {
            this.adalService.logOut();
            return false;
        } else {
            return true;
        }
    } else {
        this.adalService.login();
        return false;
    }
```
But the logout seems not work. The application doesn't go to logout redirect uri and the user seems still authenticated.

Do you have any idea what I am doing wrong? Also do you have any ideas on how to add authorization after adal authentication. 

Thanks for your help.

**Comment by benbaran** [comment]
I wonder if it may be better to split it up into two separate guards to apply to the same route?

**Comment by ricklang** [comment]
First multiple canActivate guards are harder to maintenance for large project. All the execute order is not defined. So I thought to use one canActivate guard and one resolver. Again it creates problems for adding guard and resolver to many routers.

I finally settled to use router event. Although I am still testing, looks like the logout() call does work as expected inside router event callback.
